server:
  port: ${SERVER_PORT}
#  ssl:
#    key-store-type: PKCS12
#    key-store: classpath:keystore.p12
#    key-store-password: ${SERVER_SSL_KEYSTOREPASSWORD}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        generate_statistics: false

jwt:
  access-token:
    secret: ${JWT_ACCESSTOKEN_SECRET}
  refresh-token:
    secret: ${JWT_REFRESHTOKEN_SECRET}

logging:
  level:
    org.hibernate.orm.jdbc.bind: null