server:
  port: 8080
  servlet:
    context-path: /

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: "jdbc:h2:mem:routine_connect;MODE=MYSQL;NON_KEYWORDS=USER,HOUR,DAY;DB_CLOSE_DELAY=-1"
    username: "sa"
    password: ""

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true

  jackson:
    serialization:
      fail-on-empty-beans: false

jwt:
  access-token:
    secret: "MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEArkgzz9mrm74xCsZaQuQtbrCIGfk2NaEymFf5UzKeL+O8QgrCLC9nbUHBHMjqQy3uiHm4+BMUjoSRhq6/1Qqvdpp1t6/WnLYafaZ2Iv4FTD49kvw52Drhw3ZdZMZBhAWIf8h0geG0g2AKnL2tW7bP40X3Y38uTcHAEKhCvPr30NS5ZB0/qWXMooxJ5J7aTiYgixS3lxSZv9VGG1tgbtc9qtYAvftEQnr/xWQWx26zAyqAvfc7oDUJfY+Ls5SZJ73N80w5md5AeeduEcCOtORGRJF8usySlhguMf8HWWPwvNMEeeJFT4kwwWwygbFWcd5Ai7OHAjyCITMRBvvo7AY5sPj+495pean06bXw93CO5VaRWFIRhUlmVhoJkf7PHEoXZcudyFBJ+lHb6R7+LDyc680/S/Qxh2R6/lukXTbJeAM3q/H0LNK95rbf6jjzZ06xVXG3e5SXYftbrpI7ImsKwvLSTEjOeasX5cP7PBn8DwmwHkcLAESeEVLpWe0sQstOhBGlqdyO6KCTG2wj8KNoVspD92brTrELcTRlNleY4DuvjG1jRvu7DaPH0tARbO0jmzuW+OzwrRaWBnn2DpACuYItUcO41kvjAgqVrzIrWvAGJeXc9hi8TGeIF+JqBp4MUNcCefpnBU7pXnp/h+o2tGMRP48W/feUcPVs7EiIe/cCAwEAAQ=="
    expiration-minute: 5
  refresh-token:
    secret: "MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEApbD2MuKrh9nqYhR6LfeYlu6z2+N2h7dlvmFS7aAs1zYNAQWlDdBka9AoQo+4l8H82mA7GEJZzy4zM7n2+QTD8gmtaGoOpEgS03TzQxRmrH3KbBCadC53x7/0IhHYFDju8xfK9A7UTd9BqU9l2DOO2q1TBlerwBLfOLKq/0bws+jjMDHykhtAjWoLmmvfWf4v066aaOk/wc+IVu+h5+FOfhz2izPy2bUYv+eKvmktyOiBvjF/3GXWN5ijrg+tH/sUX3V3LWFIMIvtSMgzvOe3Kn1w8JLpc/jQoMsOK/DHLC6ou4ccCh6K7nVJ3K6Gm5OCtkEj/wfZkg53ftYDQl2LVtRi4uuVC7fO7jaZ9vZnXRFbLdQ6T3qoJaKoxB7ipRRdwGkPXCa/j9SkDT4xzeGa8NcBnvfzQq5Hh8sBfdSO9X2aMQJmKfdnb15mJVqyYOrZ6e0IGI1k2bloDttpKpGA4t2N0s0Y2Lufvkioop1NTVQelgh7g2eVlhrxVHzW0S8rbTh1saB0nenGtTxIlz9JKzDc+Pkz9KSsXvpTdx++ECF5jgOYIs0pJQGE1WbIn8L+v8Wa9oyhN2xVqC8UhA1EEFVtFQtSXfeofQx86F2UbsXz2waJQLQd3yNVKDOU0iiGxMLW5kY8+gKX+6CkdmNPkI1ZQWIkavhfH7V5ZE6g2l8CAwEAAQ=="
    expiration-hour: 1

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE