name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APPLICATION_NAME: routine-connect
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Create document and build for merge to dev branch
        if: github.ref == 'refs/heads/dev'
        run: |
          ./gradlew asciidoctor
          ./gradlew build -x test

      - name: Build with Gradle for main branch and pull request for dev branch
        if: github.ref == 'refs/heads/main' || github.base_ref == 'dev'
        run: ./gradlew build

      - name: Archive application
        if: github.event_name == 'push'
        run: |
          mkdir temp
          cp build/libs/*.jar temp/
          mkdir temp/scripts
          cp scripts/* temp/scripts
          tar cvfz ${{ env.APPLICATION_NAME }}.tar.gz temp/

      - name: Upload Artifact to OCI Object Storage
        if: github.event_name == 'push'
        uses: oracle-actions/run-oci-cli-command@v1.3.2
        with:
          command: "os object put --bucket-name ${{ vars.OCI_BUCKET_NAME }} --file ${{ env.APPLICATION_NAME }}.tar.gz --name deploy/${{ env.APPLICATION_NAME }}.tar.gz --force"

      - name: Deploy to OCI Compute Instance via SSH
        uses: appleboy/ssh-action@v1.2.0
        if: github.event_name == 'push'
        with:
          host: ${{ vars.OCI_INSTANCE_URL }}
          username: ubuntu
          key: ${{ secrets.OCI_INSTANCE_PRIVATE_KEY }}
          port: 22
          script: |
            export PATH=$HOME/bin:$PATH
            cd /home/ubuntu/routine-connect
            oci os object get --bucket-name ${{ vars.OCI_BUCKET_NAME }} \
                              --name deploy/${{ env.APPLICATION_NAME }}.tar.gz \
                              --file ${{ env.APPLICATION_NAME }}.tar.gz
            tar --overwrite -xzvf ${{ env.APPLICATION_NAME }}.tar.gz --strip-components=1
            bash scripts/stop-server.sh
            bash scripts/start-server.sh
